language: objective-c
cache: cocoapods
osx_image: xcode8.3

notifications:
#  email: 
#  - lduraes@gmail.com
  
  slack:
  - mob4u:PlQsur38iWC4HpLBx4IahnaL

before_install:
  - gem update fastlane --no-ri --no-rdoc --no-document
  - gem install xcov --no-ri --no-rdoc --no-document

script: travis/script.sh
after_sucess: travis/after_success.sh

