language: objective-c
cache: cocoapods
osx_image: xcode8.3

notifications:
  email: 
  - lduraes@gmail.com
  
  slack:
  - mob4u:PlQsur38iWC4HpLBx4IahnaL

before_install:
  - gem update fastlane --no-ri --no-rdoc --no-document
  - gem install xcov --no-ri --no-rdoc --no-document

script: travis/script.sh
after_sucess: travis/after_success.sh

#xcode_workspace: ACTest/ACTest.xcworkspace
#xcode_scheme: ACTest/ACTest

##podfile: ACTest/Podfile
##before_install:
##- pod install

##script:
##- xcodebuild -workspace ACTest.xcworkspace -scheme ACTest -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO #build | xcpretty - c
##- xctool test -workspace ACTest.xcworkspace -scheme ACTestTests -sdl iphonesimulator ONLY_ACTIVE_ARCH=NO
#xcode_project: ACTest/ACTest.xcodeproj

#xcode_sdk: 
